---
# suse-ses-prepare_minions/tasks/main.yml

- name: "Install salt-minion package(s)"
  package:
    name: "{{ salt_minion_packages }}"

- name: "Add salt master to /etc/hosts"
  lineinfile:
    path: "/etc/hosts"
    # better not match the exact line, otherwise an additional space will result in duplicate lines
    # or a missing FQDN will not be fixed, but a duplicate line inserted...
    # regexp: "^{{ internal_ip | default( ansible_default_ipv4['address'] ) }}.*{{ inventory_hostname }}.*{{ inventory_hostname }}.{{ domain_name }}"
    regexp: "{{ item }}"
    line: "{{ hostvars[item]['internal_ip'] | default( hostvars[item]['ansible_default_ipv4']['address'] ) }} {{ item }} {{ item }}.{{ domain_name }}"
  with_items: "{{ groups['admin_node'] }}"

- name: "Add salt master IP to /etc/salt/minion.d/master.conf"
  template:
    src: "etc_salt_minion.d_master.conf.j2"
    dest: "/etc/salt/minion.d/master.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Restart salt-minion service"

- name: "Add hostname to /etc/salt/minion_id"
  template:
    src: "etc_salt_minion_id.j2"
    dest: "/etc/salt/minion_id"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Restart salt-minion service"

- name: "Add deepsea to /etc/salt/grains"
  template:
    src: "etc_salt_grains.j2"
    dest: "/etc/salt/grains"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Restart salt-minion service"

- name: "Start salt-minion service"
  service:
    name: "{{ salt_minion_service }}"
    state: "started"
    enabled: true
